apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: test-argo
spec:
  project: taind-lab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  source:
    repoURL: https://spartan-stratos.github.io/helm-charts
    chart: spartan
    targetRevision: 0.1.8
    helm:
      releaseName: test-argo
      valuesObject:
        replicaCount: 1
        image:
          # This is the image of the application
          repository: ghcr.io/poc-gitops/web-platform/web-platform
          tag: m-testing # This is the commit hash of the image
        containerPort: 80
        ingress:
          enabled: true
          className: "cloudflare-tunnel"
          hosts:
            - host: web-platform-dev.mhcp001.uk
              paths:
                - path: /
                  pathType: ImplementationSpecific
